seismicpro/models/unet_attention.py
seismicpro/src/seismic_batch.py

This pull request is aimed to add an oppotunity to copy meta information from one component to another. Only one action `copy_meta` contains here.
We need this because there are actions that use meta data inside:
* _dump_split_segy
* _dump_picking
* hodograph_straightening
* calculate_semblance
Without coping meta we aren't able to use them with any components, we can use them only will component with loaded data inside (usually 'raw').

add copy_meta action

---

seismicpro/src/plot_utils.py

When several arrays with different shapes are passed to `seismic_plot` and `xlim, ylim` are not set, resulting plots have the same shape, which is the shape of the array that is listed first
This PR fixes this error

fix x_lim, y_lim

---

seismicpro/src/seismic_batch.py

If you create component by hands it wound't have a meta at all. Old `copy_meta` always is tried to find new component in meta and fails if the component is not contained in the meta dict.
Moreover, this PR is added  empty meta for components that was created by `add_components` action.

Fix bug in meta

---

seismicpro/src/utils/file_utils.py

* Speed up `aggregate_segys` in case of a large number of input files (> 10000) by avoiding opening all of them at once
* Set default `mmap` value to `False` since it improves performance for small input files (the most common use case)
* Fix a progress bar to represent the actual execution status by moving it to the outermost loop
* Add a flag to delete input files after aggregation

Optimize segy files aggregation

---

seismicpro/src/batch.py

* Add no_eval mode for dst parameter in `split_model_outputs` function if NamedExpression is passed.
* Fix raise when given dst has wrong type

fix split_model_outputs

---

seismicpro/src/dataset.py
seismicpro/src/decorators.py
seismicpro/src/index.py
seismicpro/src/utils/general_utils.py

* Fix `SeismicIndex.reindex`:
* Now iteration is allowed over reindexed instance,
* Now it's possible to optionally reindex all nested indices (`train`, `test` and `validation`),
* Reindexing of underlying surveys is now optional.
* Add reindex to `SeismicDataset` which simply reindexes its `index` attribute

reindex improvements

---

seismicpro/src/batch.py

Add option to pass array-like to split_model_outputs as `src`.

fix split_model_outputs function

---

seismicpro/src/survey.py
seismicpro/src/tests/gather_test.py

keeping dead trace indicator in headers allows convenient fitering

mark dead traces

---

seismicpro/src/batch.py
seismicpro/src/decorators.py
seismicpro/src/gather.py
seismicpro/src/semblance.py
seismicpro/src/utils/plot_utils.py

Changes summary:
* `gather.plot` with `'hist'` mode can plot histograms of gather data amplitudes or gather's header values;
* now `gather.plot` has `x_tick_src` \ `y_tick_src` parameters that indicate the data source and default label for said axes; `'label'` key of `x\y_ticker` parameter now only controls axis label and can overwrite default provided by `x\y_tick_src`;
* text formatting was moved from `@plotter` decorator to the body of corresponding plot methods, since only plot methods know which of their arguments should be treated as text parameters.
* `None` value is now allowed for `tick_labels` in `set_ticks` function; in this case, all the formatting and locating options (except for `step_labels`, for obvious reasons) are applied to default ticks;
Also, fixed of a small bug in …

Add "hist" mode in `gather.plot`

---

seismicpro/src/survey.py
seismicpro/src/tests/survey/test_stats.py

Dead traces detection works slowly compared to `collect_stats` due to slow work of `np.isclose` for scalars (https://github.com/numpy/numpy/issues/16160) 
I've replaced np.isclose with math.isclose in `mark_dead_traces` and added various survey indices in dead traces related tests
here (https://github.com/numpy/numpy/issues/10161) some differences in np.isclose and math.isclose are discussed

fix speed, add test params

---

seismicpro/src/gather/gather.py

1. Fasten plot by using custom `Artists` to plot the same figures.
2. Add default estimation for `lw` and `alpha` parameters which heavily affect how gather is being plotted.
On the left `gather.plot(mode='wiggle)` from master, on the right the same call from this PR. Note the computational times in the titles.

Faster and clearer wiggle plot

---

seismicpro/refractor_velocity/refractor_velocity.py
seismicpro/refractor_velocity/refractor_velocity_field.py

Speed up `RefractorVelocityField.from_survey` and `RefractorVelocityField.refine` by fitting near-surface velocity models in separate processes. Timings for the last large survey:
| Supergather step | Number of gathers | Master version | Proposed version | Speedup |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 20 | 4614 | 47s | 6s | 8x |
| 10 | 18337 | 179s | 20s | 9x |
| 5 | 73070 | 721s | 57s | 13x |

Implement parallel calculation and refinement of RVF

---

seismicpro/gather/gather.py

`gather.plot(mode='wiggle')` takes 15sec to execute for `matplotlib==3.6.1`
The matplotlib artist represening our wiggle curve is `Path`.  Starting [from](https://github.com/matplotlib/matplotlib/pull/19214),  slow fancy logic used for this artist to`autoscale`. 
It scales linearly with `len(Path)` , we have `len(Path) ~ gather.n_times * gather.n_traces`.
Temproary disable `autoscale` via not optimal `add_artist` API, waiting for proper [API](https://github.com/matplotlib/matplotlib/pull/15595) to release

Bump matplotlib version

---

benchmark/utils.py
seismicpro/containers.py
seismicpro/gather/gather.py
seismicpro/gather/metrics.py
seismicpro/index.py
seismicpro/refractor_velocity/refractor_velocity.py
seismicpro/survey/survey.py
seismicpro/tests/survey/test_load_gather.py
seismicpro/tests/test_gather.py
seismicpro/utils/general_utils.py

1. Now the following code
```python
offset = gather["offset"]
```
returns a 1d array instead of 2d. Old behavior can be obtained by always passing a list of headers similar to `pandas` convention:
```python
offset_2d = gather[["offset"]]
```
2. Now `__setitem__` of trace containers acts identically to that of a `pd.DataFrame`. Previously the following code worked:
```python
survey[["my_header"]] = np.arange(survey.n_traces)
```
Now, following the `pandas` convention, it raises an error. Two valid options are:
```python
survey["my_header"] = np.arange(survey.n_traces)
survey[["my_header"]] = np.arange(survey.n_traces).reshape(-1, 1)
```
3. Simplifies `IndexPart` instantiation a bit.

Return a 1d-array for a single header selection 

---

seismicpro/const.py
seismicpro/gather/gather.py
seismicpro/index.py
seismicpro/survey/survey.py
seismicpro/tests/survey/asserters.py
seismicpro/tests/survey/conftest.py
seismicpro/tests/survey/test_init.py
seismicpro/tests/survey/test_reindex.py
seismicpro/tests/test_batch.py
seismicpro/tests/test_dump_merge.py
seismicpro/tests/test_gather.py
seismicpro/tests/test_index_dataset.py
seismicpro/tests/test_segy_generator.py

New features:
* A new method to `Gather`. This method provided an abilibty to save any columns from `Gather` to the parent `Survey`. 
* Tests for this method.
* Add `validate=False` for all tests where new Survey was created to avoid a bunch or useless warnings and speed up testing process.
* Add validate as a parameter to Survey testing
* Fix other tests that failed thanks to new method
Used in pipeline, method `store_headers_to_survey` (any suggestions about naming are highly welcome) will save columns to `Survey` that generated certain `Gather` object.

Store headers from gather to survey

---

seismicpro/gather/gather.py
seismicpro/refractor_velocity/refractor_velocity.py
seismicpro/semblance/semblance.py
seismicpro/stacking_velocity/metrics.py
seismicpro/tests/test_gather.py
seismicpro/utils/plot_utils.py

`gather.sort()` now can work with multiple headers, e.g. `gather.sort(['INLINE_3D', 'CROSSLINE_3D'])`
The `gather.sort_by` attribute is latter is used in `gather.plot()` to infer axis ticks. 
In case `gather` is sorted by two headers, add minor ticks to handle minor header, e.g.
`gather.sort(['SourceWaterDepath', 'GroupWaterDepth']).plot()`

Sort gather by multiple headers

---

seismicpro/field.py
seismicpro/muter/muter_field.py
seismicpro/refractor_velocity/interactive_plot.py
seismicpro/refractor_velocity/refractor_velocity.py
seismicpro/refractor_velocity/refractor_velocity_field.py
seismicpro/stacking_velocity/stacking_velocity_field.py
seismicpro/utils/coordinates.py
seismicpro/utils/interpolation/spatial.py

Fixed several small bugs appeared during processing of last surveys:
* Now `RefractorVelocity.__getattr__` works as expected: previously `rv.t0` failed,
* Added tolerances in `RefractorVelocity._validate_params` checks. Previously they may have failed to fit a velocity model for noisy first breaks. Was also mentioned in https://github.com/gazprom-neft/SeismicPro/pull/107, but not completely fixed,
* Fixed a rare bug when IDW interpolation within a given radius resulted in `nan` values due to inaccuracies in floating-point arithmetics,
* Fixed processing of `coords_cols` during a field update: e.g. previously `RefractorVelocityField.from_survey(survey, n_refractors=1, is_geographic=True)` produced wrong results if `survey` was indexed by line-based coordinates.

Fields bugfixes

---

seismicpro/containers.py
seismicpro/gather/gather.py
seismicpro/gather/metrics.py
seismicpro/metrics/interactive_map.py
seismicpro/refractor_velocity/refractor_velocity.py
seismicpro/refractor_velocity/refractor_velocity_field.py
seismicpro/refractor_velocity/utils.py
seismicpro/survey/headers.py
seismicpro/survey/survey.py
seismicpro/tests/test_dump_merge.py
seismicpro/tests/test_segy_generator.py
seismicpro/utils/interactive_plot_utils.py
seismicpro/utils/interpolation/spatial.py
seismicpro/utils/interpolation/univariate.py

- `Survey` now has an `is_uphole` property, which is calculated by values of `SourceUpholeTime` and `SourceDepth` headers if they are loaded. Consistency of these headers is now checked in `validate_headers`.
- `Gather.calculate_refractor_velocity` and `RefractorVelocityField.from_survey` now accept a `correct_uphole` flag which specifies whether to perform uphole correction by adding values of `SourceUpholeTime` header to times of first breaks or not. This emulates the case when sources are located on the surface. By default, correction is performed if `SourceUpholeTime` header is loaded.
- `RefractorVelocity` now has an `is_uphole_corrected` attribute which is set on construction. `RefractorVelocityField` now has an `is_uphole_corrected` property which is inferred by its items.
- …

Handle uphole correction

---

seismicpro/containers.py
seismicpro/dataset.py
seismicpro/gather/gather.py
seismicpro/index.py
seismicpro/refractor_velocity/refractor_velocity_field.py
seismicpro/survey/headers.py
seismicpro/survey/headers_checks.py
seismicpro/survey/metrics.py
seismicpro/survey/plot_geometry.py
seismicpro/survey/survey.py
seismicpro/utils/coordinates.py

- Two new survey attributes are introduced: `source_id_cols` and `receiver_id_cols`, which store names of trace headers that uniquely identify a seismic source or receiver respectively. They can be passed either directly to the `Survey.__init__` or subsequently using `set_source_id_cols` and `set_receiver_id_cols` methods.
- `n_sources` and `n_receivers` properties are also introduced. They are also printed in `info` (wow!)
- All survey plotters now account for these attributes (including `construct_fold_map`, `construct_header_map` and `plot_geometry`),
- Prettify validation of survey headers:
- Some extra checks were added,
- Now all checks return the number and fraction of "bad" traces/sources/receivers

Introduce source and receiver ID cols

---

seismicpro/gather/gather.py

Avoid numpy array creation in `gather.__getitem__`, since it fails if when key has inhomogeneous shape.

Hotfix for gather getitem

---

seismicpro/__init__.py
seismicpro/batch.py
seismicpro/config.py
seismicpro/dataset.py
seismicpro/gather/gather.py
seismicpro/survey/survey.py

* Add a global `SeismicPro` config inspired by that of `pandas`, now it contains a single option `enable_fast_pickling`.
* If this option is enabled, several objects such as `SeismicDataset` or `Survey` stop pickling their most memory-intensive attributes such as `headers`.
* This allows for huge time and memory savings when running  pipelines with `mpc` prefetch. The most common case is seismic cube stacking pipeline.
* In order to speed it up even more, two more enhancements are introduced:
* Implement `SeismicBatch.combine_gathers` method which combines gathers loaded from the same `Survey` into a single gather. This allows for more efficient `dump` since text and bin headers are stored only once (which especially matters when dumping a single stacked trace) and speeds up subsequent …

Speed up cube stacking

---

seismicpro/survey/survey.py
setup.py

Some SEG-Y files contain empty or invalid (e.g. negative) sample interval. Such files cannot be opened with `SeismicPro` and require file data to be changed even if the actual sample interval is known.
This pull request allows passing `sample_interval` and `delay` directly to `Survey.__init__`: the passed values will override those stored in file headers.

Allow passing sample_interval and delay upon Survey construction
